version: '3.8'
services:
  mongodb:
    image: mongo:8.0.0
    container_name: mongodb
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

  api:
    container_name: api
    build: .
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb
    command: npm run start:prod
